- src/lib/convert.ts
Fix this error when having a folder in the source dir :
`svg-to-ts: Something went wrong Error: EISDIR: illegal operation on a directory, read`.
It's my first pull request, tell me if there's anything to change/modify.
> fix(input): Exclude folders to source directory

- src/lib/convert.ts
Fix #14 ; add a test to allow only .svg files
> fix(conversion): check to allow only svg files

- src/lib/helpers/file-helpers.ts
- src/lib/helpers/svg-optimization.ts
- src/lib/options/convertion-options.ts
For more details check: https://eslint.org/docs/rules/no-return-await
> Remove unnecessary return await

- README.md
BREAKING CHANGE: conversion option is required
> feat(options): add conversion options

- package.json
- src/lib/converters/files.converter.ts
- src/lib/options/args-collector.ts
- src/lib/options/conversion-options.ts
- src/lib/options/default-options.ts
Allows customization of barrel file name #32
> feat(files-converter) configurable barrel filename

- src/lib/options/config-collector.ts
fix check to detect if default option is provided or not
> fix: 🐛 default options

- README.md
- src/bin/svg-to-ts.ts
- src/lib/options/command-line-collector.ts
- src/lib/options/config-collector.ts
- src/lib/options/conversion-options.ts
add config option to support custom configuration path
✅ Closes: #67
> feat: 🎸 configuration path

- src/lib/converters/constants.converter.ts
- src/lib/converters/files.converter.ts
- src/lib/generators/code-snippet-generators.spec.ts
- src/lib/generators/code-snippet-generators.ts
> fix: 🐛 generate correct interface for SVG contants

- src/lib/converters/shared.converter.ts
> fix: 🐛 handle file names with special characters

- CONTRIBUTING.md
- commitlint.config.js
- package-lock.json
- package.json
Hi @kreuzerk. I found myself with a bit of capacity and hope you don't mind me suggesting a few potential improvements? Mostly around the structure and tooling of the repo as opposed to the actual library code, absolutely no pressure to merge if you aren't sure.
The work in this PR was concerned with tightening up the commit formatting. I've added...
- [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) configuration to the existing commitizen setup, this provides a cli step through of the formatting for people who want to use it. 
- [commitlint](https://www.npmjs.com/package/commitlint) to husky just to make sure the commit message is followed.
- the start of a Contribution doc which mostly outlines the above
Apologies for just jumping on in there, I can raise issues if …
> Commit formatting

- src/lib/converters/files.converter.ts
> Update complete icon set file name

- src/bin/svg-to-ts-constants.ts
- src/bin/svg-to-ts-files.ts
- src/bin/svg-to-ts-object.ts
> fix(infomessage): log correct conversion type

- src/bin/svg-to-ts-constants.ts
- src/bin/svg-to-ts-files.ts
- src/bin/svg-to-ts-object.ts
- src/lib/options/options-collector/config-file-options-collector/config-file-constants-options.collector.ts
- src/lib/options/options-collector/config-file-options-collector/config-file-files-options.collector.ts
- src/lib/options/options-collector/config-file-options-collector/config-file-object-options.collector.ts
> fix(flag handling): only apply default for non provided flags

- README.md
> docs(constants): update docs for generated constants

- README.md
- package.json
- src/lib/converters/object.converter.ts
- src/lib/generators/code-snippet-generators.spec.ts
- src/lib/generators/code-snippet-generators.ts
- src/lib/options/commander/object-options.commander.ts
- src/lib/options/conversion-options/object-conversion-options.ts
- src/lib/options/default-options/default-object-conversion-options.ts
- src/lib/options/options-collector/command-line-options-collectors/commandline-object-options.collector.ts
- src/lib/options/options-collector/config-file-options-collector/config-file-object-options.collector.ts
Voila!
https://github.com/kreuzerk/svg-to-ts/issues/137
> feat(converter): add typeName for object generation

- src/lib/converters/constants.converter.ts
- src/lib/options/options-collector/config-file-options-collector/config-file-constants-options.collector.ts
> feat(enum): generate enums for constants

- src/lib/generators/code-snippet-generators.spec.ts
> chore: fix typo in code-snippet-generators.spec.ts

- README.md
I have replaced all `additionalModelFile` with `additionalModelOutputPath` in all examples in README
> Replaced additionalModelFile

- README.md
Also added the clarification for the `optimizeForLazyLoading` option because it was not so clear if it is still supported or not as it is.
> Minor corrections in README.md

- README.md
I think this readme might have been slightly outdated with the sample so i made an adjustment. I hope this helps! Thanks
> Adjust compilationOutput sample package.json references in README.MD

- src/lib/generators/code-snippet-generators.spec.ts
- src/lib/generators/code-snippet-generators.ts
> fix(tsx): use the correct type for tsx props
